import type { Author, Book } from "./types";
import { getNormalizedAssetUrl } from "./normalizedAssets";
import { BATCH50_GUTENBERG_IDS } from "./batch50SourceIds";

export const BATCH50_AUTHORS: Author[] = [
  { id: "dickens", name: "Чарльз Диккенс", alternativeNames: ["Charles Dickens"], birthYear: 1812, deathYear: 1870 },
  { id: "charlotte-bronte", name: "Шарлотта Бронте", alternativeNames: ["Charlotte Brontë", "Charlotte Bronte"], birthYear: 1816, deathYear: 1855 },
  { id: "emily-bronte", name: "Эмили Бронте", alternativeNames: ["Emily Brontë", "Emily Bronte"], birthYear: 1818, deathYear: 1848 },
  { id: "anne-bronte", name: "Энн Бронте", alternativeNames: ["Anne Brontë", "Anne Bronte"], birthYear: 1820, deathYear: 1849 },
  { id: "george-eliot", name: "Джордж Элиот", alternativeNames: ["George Eliot", "Mary Ann Evans"], birthYear: 1819, deathYear: 1880 },
  { id: "thomas-hardy", name: "Томас Харди", alternativeNames: ["Thomas Hardy"], birthYear: 1840, deathYear: 1928 },
  { id: "joseph-conrad", name: "Джозеф Конрад", alternativeNames: ["Joseph Conrad", "Józef Teodor Konrad Korzeniowski"], birthYear: 1857, deathYear: 1924 },
  { id: "stevenson", name: "Роберт Льюис Стивенсон", alternativeNames: ["Robert Louis Stevenson"], birthYear: 1850, deathYear: 1894 },
  { id: "melville", name: "Герман Мелвилл", alternativeNames: ["Herman Melville"], birthYear: 1819, deathYear: 1891 },
  { id: "wharton", name: "Эдит Уортон", alternativeNames: ["Edith Wharton"], birthYear: 1862, deathYear: 1937 },
  { id: "henry-james", name: "Генри Джеймс", alternativeNames: ["Henry James"], birthYear: 1843, deathYear: 1916 },
  { id: "joyce", name: "Джеймс Джойс", alternativeNames: ["James Joyce"], birthYear: 1882, deathYear: 1941 },
  { id: "fitzgerald", name: "Фрэнсис Скотт Фицджеральд", alternativeNames: ["F. Scott Fitzgerald", "Francis Scott Fitzgerald"], birthYear: 1896, deathYear: 1940 },
  { id: "dh-lawrence", name: "Дэвид Герберт Лоуренс", alternativeNames: ["D. H. Lawrence", "David Herbert Lawrence"], birthYear: 1885, deathYear: 1930 }
];

function edition(workId: string) {
  const url = getNormalizedAssetUrl(workId);
  if (!url) throw new Error(`Missing normalized asset registration for ${workId}`);
  const externalId = BATCH50_GUTENBERG_IDS[workId];
  return {
    id: `${workId}-gutenberg-${externalId ?? "normalized"}`,
    language: "en",
    isOriginal: true,
    translatorName: null,
    rights: [{ status: "public-domain" as const, jurisdiction: "US", assessedBy: "source" as const }],
    sourceId: "gutenberg",
    externalIds: externalId ? { gutenberg: externalId } : {},
    files: [{ format: "anki-json" as const, url }]
  };
}

export const BATCH50_BOOKS: Book[] = [
  { id: "sense-and-sensibility", title: "Sense and Sensibility", originalTitle: "Sense and Sensibility", alternativeTitles: [], authorId: "austen", authorName: "Джейн Остин", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1811, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["family", "love", "society"], description: "", cover: null, editions: [edition("sense-and-sensibility")], collectionIds: [] },
  { id: "emma", title: "Emma", originalTitle: "Emma", alternativeTitles: [], authorId: "austen", authorName: "Джейн Остин", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1815, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "love"], description: "", cover: null, editions: [edition("emma")], collectionIds: [] },
  { id: "mansfield-park", title: "Mansfield Park", originalTitle: "Mansfield Park", alternativeTitles: [], authorId: "austen", authorName: "Джейн Остин", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1814, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["family", "society"], description: "", cover: null, editions: [edition("mansfield-park")], collectionIds: [] },
  { id: "northanger-abbey", title: "Northanger Abbey", originalTitle: "Northanger Abbey", alternativeTitles: [], authorId: "austen", authorName: "Джейн Остин", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1817, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["coming-of-age", "society"], description: "", cover: null, editions: [edition("northanger-abbey")], collectionIds: [] },
  { id: "persuasion", title: "Persuasion", originalTitle: "Persuasion", alternativeTitles: [], authorId: "austen", authorName: "Джейн Остин", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1817, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["love", "society"], description: "", cover: null, editions: [edition("persuasion")], collectionIds: [] },
  { id: "oliver-twist", title: "Oliver Twist", originalTitle: "Oliver Twist", alternativeTitles: [], authorId: "dickens", authorName: "Чарльз Диккенс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1838, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "coming-of-age"], description: "", cover: null, editions: [edition("oliver-twist")], collectionIds: [] },
  { id: "great-expectations", title: "Great Expectations", originalTitle: "Great Expectations", alternativeTitles: [], authorId: "dickens", authorName: "Чарльз Диккенс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1861, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["coming-of-age", "society", "identity"], description: "", cover: null, editions: [edition("great-expectations")], collectionIds: [] },
  { id: "a-tale-of-two-cities", title: "A Tale of Two Cities", originalTitle: "A Tale of Two Cities", alternativeTitles: [], authorId: "dickens", authorName: "Чарльз Диккенс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1859, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "death"], description: "", cover: null, editions: [edition("a-tale-of-two-cities")], collectionIds: [] },
  { id: "david-copperfield", title: "David Copperfield", originalTitle: "David Copperfield", alternativeTitles: [], authorId: "dickens", authorName: "Чарльз Диккенс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1850, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["coming-of-age", "identity"], description: "", cover: null, editions: [edition("david-copperfield")], collectionIds: [] },
  { id: "bleak-house", title: "Bleak House", originalTitle: "Bleak House", alternativeTitles: [], authorId: "dickens", authorName: "Чарльз Диккенс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1853, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "family"], description: "", cover: null, editions: [edition("bleak-house")], collectionIds: [] },
  { id: "hard-times", title: "Hard Times", originalTitle: "Hard Times", alternativeTitles: [], authorId: "dickens", authorName: "Чарльз Диккенс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1854, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "power"], description: "", cover: null, editions: [edition("hard-times")], collectionIds: [] },
  { id: "a-christmas-carol", title: "A Christmas Carol", originalTitle: "A Christmas Carol", alternativeTitles: [], authorId: "dickens", authorName: "Чарльз Диккенс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1843, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novella"], themeIds: ["morality", "family"], description: "", cover: null, editions: [edition("a-christmas-carol")], collectionIds: [] },
  { id: "nicholas-nickleby", title: "Nicholas Nickleby", originalTitle: "Nicholas Nickleby", alternativeTitles: [], authorId: "dickens", authorName: "Чарльз Диккенс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1839, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["family", "society"], description: "", cover: null, editions: [edition("nicholas-nickleby")], collectionIds: [] },
  { id: "jane-eyre", title: "Jane Eyre", originalTitle: "Jane Eyre", alternativeTitles: [], authorId: "charlotte-bronte", authorName: "Шарлотта Бронте", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1847, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "romanticism", genreIds: ["novel"], themeIds: ["identity", "love", "society"], description: "", cover: null, editions: [edition("jane-eyre")], collectionIds: [] },
  { id: "villette", title: "Villette", originalTitle: "Villette", alternativeTitles: [], authorId: "charlotte-bronte", authorName: "Шарлотта Бронте", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1853, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "romanticism", genreIds: ["novel"], themeIds: ["identity", "alienation"], description: "", cover: null, editions: [edition("villette")], collectionIds: [] },
  { id: "wuthering-heights", title: "Wuthering Heights", originalTitle: "Wuthering Heights", alternativeTitles: [], authorId: "emily-bronte", authorName: "Эмили Бронте", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1847, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "romanticism", genreIds: ["novel"], themeIds: ["love", "family", "death"], description: "", cover: null, editions: [edition("wuthering-heights")], collectionIds: [] },
  { id: "agnes-grey", title: "Agnes Grey", originalTitle: "Agnes Grey", alternativeTitles: [], authorId: "anne-bronte", authorName: "Энн Бронте", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1847, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "identity"], description: "", cover: null, editions: [edition("agnes-grey")], collectionIds: [] },
  { id: "tenant-of-wildfell-hall", title: "The Tenant of Wildfell Hall", originalTitle: "The Tenant of Wildfell Hall", alternativeTitles: [], authorId: "anne-bronte", authorName: "Энн Бронте", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1848, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["family", "society", "identity"], description: "", cover: null, editions: [edition("tenant-of-wildfell-hall")], collectionIds: [] },
  { id: "middlemarch", title: "Middlemarch", originalTitle: "Middlemarch", alternativeTitles: [], authorId: "george-eliot", authorName: "Джордж Элиот", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1871, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "family"], description: "", cover: null, editions: [edition("middlemarch")], collectionIds: [] },
  { id: "silas-marner", title: "Silas Marner", originalTitle: "Silas Marner", alternativeTitles: [], authorId: "george-eliot", authorName: "Джордж Элиот", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1861, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["family", "morality"], description: "", cover: null, editions: [edition("silas-marner")], collectionIds: [] },
  { id: "adam-bede", title: "Adam Bede", originalTitle: "Adam Bede", alternativeTitles: [], authorId: "george-eliot", authorName: "Джордж Элиот", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1859, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["morality", "society"], description: "", cover: null, editions: [edition("adam-bede")], collectionIds: [] },
  { id: "mill-on-the-floss", title: "The Mill on the Floss", originalTitle: "The Mill on the Floss", alternativeTitles: [], authorId: "george-eliot", authorName: "Джордж Элиот", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1860, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["family", "identity"], description: "", cover: null, editions: [edition("mill-on-the-floss")], collectionIds: [] },
  { id: "tess-of-the-durbervilles", title: "Tess of the d'Urbervilles", originalTitle: "Tess of the d'Urbervilles", alternativeTitles: [], authorId: "thomas-hardy", authorName: "Томас Харди", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1891, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "morality"], description: "", cover: null, editions: [edition("tess-of-the-durbervilles")], collectionIds: [] },
  { id: "jude-the-obscure", title: "Jude the Obscure", originalTitle: "Jude the Obscure", alternativeTitles: [], authorId: "thomas-hardy", authorName: "Томас Харди", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1895, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "alienation"], description: "", cover: null, editions: [edition("jude-the-obscure")], collectionIds: [] },
  { id: "far-from-the-madding-crowd", title: "Far from the Madding Crowd", originalTitle: "Far from the Madding Crowd", alternativeTitles: [], authorId: "thomas-hardy", authorName: "Томас Харди", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1874, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["love", "society"], description: "", cover: null, editions: [edition("far-from-the-madding-crowd")], collectionIds: [] },
  { id: "mayor-of-casterbridge", title: "The Mayor of Casterbridge", originalTitle: "The Mayor of Casterbridge", alternativeTitles: [], authorId: "thomas-hardy", authorName: "Томас Харди", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1886, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["morality", "society"], description: "", cover: null, editions: [edition("mayor-of-casterbridge")], collectionIds: [] },
  { id: "return-of-the-native", title: "The Return of the Native", originalTitle: "The Return of the Native", alternativeTitles: [], authorId: "thomas-hardy", authorName: "Томас Харди", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1878, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "identity"], description: "", cover: null, editions: [edition("return-of-the-native")], collectionIds: [] },
  { id: "heart-of-darkness", title: "Heart of Darkness", originalTitle: "Heart of Darkness", alternativeTitles: [], authorId: "joseph-conrad", authorName: "Джозеф Конрад", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1899, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "modernism", genreIds: ["novella"], themeIds: ["power", "morality", "alienation"], description: "", cover: null, editions: [edition("heart-of-darkness")], collectionIds: [] },
  { id: "lord-jim", title: "Lord Jim", originalTitle: "Lord Jim", alternativeTitles: [], authorId: "joseph-conrad", authorName: "Джозеф Конрад", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1900, countryId: "england", centuryId: "20", epochId: "modernism", movementId: "modernism", genreIds: ["novel"], themeIds: ["morality", "identity"], description: "", cover: null, editions: [edition("lord-jim")], collectionIds: [] },
  { id: "secret-agent", title: "The Secret Agent", originalTitle: "The Secret Agent", alternativeTitles: [], authorId: "joseph-conrad", authorName: "Джозеф Конрад", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1907, countryId: "england", centuryId: "20", epochId: "modernism", movementId: "modernism", genreIds: ["novel"], themeIds: ["power", "society"], description: "", cover: null, editions: [edition("secret-agent")], collectionIds: [] },
  { id: "nostromo", title: "Nostromo", originalTitle: "Nostromo", alternativeTitles: [], authorId: "joseph-conrad", authorName: "Джозеф Конрад", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1904, countryId: "england", centuryId: "20", epochId: "modernism", movementId: "modernism", genreIds: ["novel"], themeIds: ["power", "society"], description: "", cover: null, editions: [edition("nostromo")], collectionIds: [] },
  { id: "treasure-island", title: "Treasure Island", originalTitle: "Treasure Island", alternativeTitles: [], authorId: "stevenson", authorName: "Роберт Льюис Стивенсон", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1883, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "romanticism", genreIds: ["novel"], themeIds: ["coming-of-age", "power"], description: "", cover: null, editions: [edition("treasure-island")], collectionIds: [] },
  { id: "jekyll-and-hyde", title: "The Strange Case of Dr. Jekyll and Mr. Hyde", originalTitle: "The Strange Case of Dr. Jekyll and Mr. Hyde", alternativeTitles: ["Dr. Jekyll and Mr. Hyde"], authorId: "stevenson", authorName: "Роберт Льюис Стивенсон", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1886, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "romanticism", genreIds: ["novella"], themeIds: ["identity", "morality"], description: "", cover: null, editions: [edition("jekyll-and-hyde")], collectionIds: [] },
  { id: "kidnapped", title: "Kidnapped", originalTitle: "Kidnapped", alternativeTitles: [], authorId: "stevenson", authorName: "Роберт Льюис Стивенсон", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1886, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "romanticism", genreIds: ["novel"], themeIds: ["coming-of-age", "power"], description: "", cover: null, editions: [edition("kidnapped")], collectionIds: [] },
  { id: "moby-dick", title: "Moby Dick", originalTitle: "Moby-Dick; or, The Whale", alternativeTitles: ["Moby-Dick", "Moby-Dick; or, The Whale"], authorId: "melville", authorName: "Герман Мелвилл", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1851, countryId: "usa", centuryId: "19", epochId: "19th-century", movementId: "romanticism", genreIds: ["novel"], themeIds: ["power", "identity", "death"], description: "", cover: null, editions: [edition("moby-dick")], collectionIds: [] },
  { id: "typee", title: "Typee", originalTitle: "Typee", alternativeTitles: [], authorId: "melville", authorName: "Герман Мелвилл", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1846, countryId: "usa", centuryId: "19", epochId: "19th-century", movementId: "romanticism", genreIds: ["novel"], themeIds: ["society", "identity"], description: "", cover: null, editions: [edition("typee")], collectionIds: [] },
  { id: "age-of-innocence", title: "The Age of Innocence", originalTitle: "The Age of Innocence", alternativeTitles: [], authorId: "wharton", authorName: "Эдит Уортон", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1920, countryId: "usa", centuryId: "20", epochId: "modernism", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "love"], description: "", cover: null, editions: [edition("age-of-innocence")], collectionIds: [] },
  { id: "house-of-mirth", title: "The House of Mirth", originalTitle: "The House of Mirth", alternativeTitles: [], authorId: "wharton", authorName: "Эдит Уортон", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1905, countryId: "usa", centuryId: "20", epochId: "modernism", movementId: "realism", genreIds: ["novel"], themeIds: ["society", "identity"], description: "", cover: null, editions: [edition("house-of-mirth")], collectionIds: [] },
  { id: "ethan-frome", title: "Ethan Frome", originalTitle: "Ethan Frome", alternativeTitles: [], authorId: "wharton", authorName: "Эдит Уортон", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1911, countryId: "usa", centuryId: "20", epochId: "modernism", movementId: "realism", genreIds: ["novella"], themeIds: ["love", "society"], description: "", cover: null, editions: [edition("ethan-frome")], collectionIds: [] },
  { id: "turn-of-the-screw", title: "The Turn of the Screw", originalTitle: "The Turn of the Screw", alternativeTitles: [], authorId: "henry-james", authorName: "Генри Джеймс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1898, countryId: "usa", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novella"], themeIds: ["identity", "alienation"], description: "", cover: null, editions: [edition("turn-of-the-screw")], collectionIds: [] },
  { id: "portrait-of-a-lady", title: "The Portrait of a Lady", originalTitle: "The Portrait of a Lady", alternativeTitles: [], authorId: "henry-james", authorName: "Генри Джеймс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1881, countryId: "usa", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novel"], themeIds: ["identity", "society"], description: "", cover: null, editions: [edition("portrait-of-a-lady")], collectionIds: [] },
  { id: "daisy-miller", title: "Daisy Miller", originalTitle: "Daisy Miller", alternativeTitles: [], authorId: "henry-james", authorName: "Генри Джеймс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1878, countryId: "usa", centuryId: "19", epochId: "19th-century", movementId: "realism", genreIds: ["novella"], themeIds: ["society", "identity"], description: "", cover: null, editions: [edition("daisy-miller")], collectionIds: [] },
  { id: "dubliners", title: "Dubliners", originalTitle: "Dubliners", alternativeTitles: [], authorId: "joyce", authorName: "Джеймс Джойс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1914, countryId: "ireland", centuryId: "20", epochId: "modernism", movementId: "modernism", genreIds: ["short-story"], themeIds: ["society", "alienation"], description: "", cover: null, editions: [edition("dubliners")], collectionIds: [] },
  { id: "portrait-of-the-artist", title: "A Portrait of the Artist as a Young Man", originalTitle: "A Portrait of the Artist as a Young Man", alternativeTitles: [], authorId: "joyce", authorName: "Джеймс Джойс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1916, countryId: "ireland", centuryId: "20", epochId: "modernism", movementId: "modernism", genreIds: ["novel"], themeIds: ["coming-of-age", "identity"], description: "", cover: null, editions: [edition("portrait-of-the-artist")], collectionIds: [] },
  { id: "great-gatsby", title: "The Great Gatsby", originalTitle: "The Great Gatsby", alternativeTitles: [], authorId: "fitzgerald", authorName: "Фрэнсис Скотт Фицджеральд", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1925, countryId: "usa", centuryId: "20", epochId: "modernism", movementId: "modernism", genreIds: ["novel"], themeIds: ["society", "identity"], description: "", cover: null, editions: [edition("great-gatsby")], collectionIds: [] },
  { id: "this-side-of-paradise", title: "This Side of Paradise", originalTitle: "This Side of Paradise", alternativeTitles: [], authorId: "fitzgerald", authorName: "Фрэнсис Скотт Фицджеральд", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1920, countryId: "usa", centuryId: "20", epochId: "modernism", movementId: "modernism", genreIds: ["novel"], themeIds: ["coming-of-age", "society"], description: "", cover: null, editions: [edition("this-side-of-paradise")], collectionIds: [] },
  { id: "sons-and-lovers", title: "Sons and Lovers", originalTitle: "Sons and Lovers", alternativeTitles: [], authorId: "dh-lawrence", authorName: "Дэвид Герберт Лоуренс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1913, countryId: "england", centuryId: "20", epochId: "modernism", movementId: "modernism", genreIds: ["novel"], themeIds: ["family", "identity"], description: "", cover: null, editions: [edition("sons-and-lovers")], collectionIds: [] },
  { id: "women-in-love", title: "Women in Love", originalTitle: "Women in Love", alternativeTitles: [], authorId: "dh-lawrence", authorName: "Дэвид Герберт Лоуренс", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1920, countryId: "england", centuryId: "20", epochId: "modernism", movementId: "modernism", genreIds: ["novel"], themeIds: ["love", "identity"], description: "", cover: null, editions: [edition("women-in-love")], collectionIds: [] },
  { id: "importance-of-being-earnest", title: "The Importance of Being Earnest", originalTitle: "The Importance of Being Earnest", alternativeTitles: [], authorId: "wilde", authorName: "Оскар Уайльд", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1895, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "aestheticism", genreIds: ["drama"], themeIds: ["society", "identity"], description: "", cover: null, editions: [edition("importance-of-being-earnest")], collectionIds: [] },
  { id: "canterville-ghost", title: "The Canterville Ghost", originalTitle: "The Canterville Ghost", alternativeTitles: [], authorId: "wilde", authorName: "Оскар Уайльд", originalLanguage: "en", availableLanguages: ["en"], publicationYear: 1887, countryId: "england", centuryId: "19", epochId: "19th-century", movementId: "aestheticism", genreIds: ["novella"], themeIds: ["society", "identity"], description: "", cover: null, editions: [edition("canterville-ghost")], collectionIds: [] }
];
