import type { Book } from "./types";

// Seed catalog for Phase 4 — ~20-30 real works across different
// authors and epochs, enough to exercise the data model and, later,
// ranking. Only "Антихрист" (Nietzsche) has a real file — it is the
// existing public/books/antichrist.txt, unchanged and untouched.
// Every other book intentionally has an empty `files` array: this
// catalog is not wired into the reader in this phase, so there is
// nothing to host yet, per confirmed scope.
export const books: Book[] = [

  {
    id: "war-and-peace",
    title: "Война и мир",
    originalTitle: "Война и миръ",
    alternativeTitles: ["War and Peace"],
    authorId: "tolstoy",
    authorName: "Лев Толстой",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1869,
    countryId: "russia",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["novel"],
    themeIds: ["war-and-peace", "family", "society"],
    description: "Эпопея о русском обществе на фоне наполеоновских войн.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["russian-classics", "great-19th-century-novels"]
  },
  {
    id: "anna-karenina",
    title: "Анна Каренина",
    originalTitle: null,
    alternativeTitles: ["Anna Karenina"],
    authorId: "tolstoy",
    authorName: "Лев Толстой",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1877,
    countryId: "russia",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["novel"],
    themeIds: ["love", "family", "society"],
    description: "Трагедия личного выбора внутри жёстких правил светского общества.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["russian-classics", "great-19th-century-novels"]
  },
  {
    id: "death-of-ivan-ilyich",
    title: "Смерть Ивана Ильича",
    originalTitle: null,
    alternativeTitles: ["The Death of Ivan Ilyich"],
    authorId: "tolstoy",
    authorName: "Лев Толстой",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1886,
    countryId: "russia",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["novella"],
    themeIds: ["death", "morality"],
    description: "Повесть о столкновении с неизбежностью смерти.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["russian-classics"]
  },
  {
    id: "crime-and-punishment",
    title: "Преступление и наказание",
    originalTitle: null,
    alternativeTitles: ["Crime and Punishment"],
    authorId: "dostoevsky",
    authorName: "Фёдор Достоевский",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1866,
    countryId: "russia",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["novel"],
    themeIds: ["morality", "society", "identity"],
    description: "Роман о преступлении, совести и наказании изнутри.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["russian-classics", "great-19th-century-novels"]
  },
  {
    id: "brothers-karamazov",
    title: "Братья Карамазовы",
    originalTitle: null,
    alternativeTitles: ["The Brothers Karamazov"],
    authorId: "dostoevsky",
    authorName: "Фёдор Достоевский",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1880,
    countryId: "russia",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["novel"],
    themeIds: ["faith", "family", "morality"],
    description: "Семейная драма как исследование веры, свободы и вины.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["russian-classics", "great-19th-century-novels"]
  },
  {
    id: "faust",
    title: "Фауст",
    originalTitle: "Faust",
    alternativeTitles: [],
    authorId: "goethe",
    authorName: "Иоганн Вольфганг фон Гёте",
    originalLanguage: "de",
    availableLanguages: ["de", "ru"],
    publicationYear: 1808,
    countryId: "germany",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "romanticism",
    genreIds: ["drama", "poem"],
    themeIds: ["power", "morality"],
    description: "Трагедия о сделке с дьяволом и цене знания.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["foundational-texts"]
  },
  {
    id: "sorrows-of-young-werther",
    title: "Страдания юного Вертера",
    originalTitle: "Die Leiden des jungen Werthers",
    alternativeTitles: ["The Sorrows of Young Werther"],
    authorId: "goethe",
    authorName: "Иоганн Вольфганг фон Гёте",
    originalLanguage: "de",
    availableLanguages: ["de", "ru"],
    publicationYear: 1774,
    countryId: "germany",
    centuryId: "18",
    epochId: "enlightenment",
    movementId: "sentimentalism",
    genreIds: ["novel"],
    themeIds: ["love", "death"],
    description: "Эпистолярный роман, определивший романтическую чувствительность эпохи.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: []
  },
  {
    id: "hamlet",
    title: "Гамлет",
    originalTitle: "Hamlet",
    alternativeTitles: ["The Tragedy of Hamlet, Prince of Denmark"],
    authorId: "shakespeare",
    authorName: "Уильям Шекспир",
    originalLanguage: "en",
    availableLanguages: ["en", "ru"],
    publicationYear: 1600,
    countryId: "england",
    centuryId: "17",
    epochId: "renaissance",
    movementId: "renaissance-drama",
    genreIds: ["tragedy", "drama"],
    themeIds: ["revenge", "power", "death"],
    description: "Трагедия мести, долга и сомнения.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["foundational-texts"]
  },
  {
    id: "romeo-and-juliet",
    title: "Ромео и Джульетта",
    originalTitle: "Romeo and Juliet",
    alternativeTitles: [],
    authorId: "shakespeare",
    authorName: "Уильям Шекспир",
    originalLanguage: "en",
    availableLanguages: ["en", "ru"],
    publicationYear: 1597,
    countryId: "england",
    centuryId: "16",
    epochId: "renaissance",
    movementId: "renaissance-drama",
    genreIds: ["tragedy", "drama"],
    themeIds: ["love", "family"],
    description: "Трагедия любви, разбивающейся о вражду двух семей.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: []
  },
  {
    id: "divine-comedy",
    title: "Божественная комедия",
    originalTitle: "Divina Commedia",
    alternativeTitles: ["La Divina Commedia"],
    authorId: "dante",
    authorName: "Данте Алигьери",
    originalLanguage: "it",
    availableLanguages: ["it", "ru"],
    publicationYear: 1320,
    countryId: "italy",
    centuryId: "14",
    epochId: "medieval",
    movementId: "medieval-poetry",
    genreIds: ["epic-poem", "poem"],
    themeIds: ["faith", "morality"],
    description: "Путешествие через ад, чистилище и рай как карта человеческой души.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["foundational-texts"]
  },
  {
    id: "beyond-good-and-evil",
    title: "По ту сторону добра и зла",
    originalTitle: "Jenseits von Gut und Böse",
    alternativeTitles: ["Beyond Good and Evil"],
    authorId: "nietzsche",
    authorName: "Фридрих Ницше",
    originalLanguage: "de",
    availableLanguages: ["de", "ru"],
    publicationYear: 1886,
    countryId: "germany",
    centuryId: "19",
    epochId: "19th-century",
    movementId: null,
    genreIds: ["philosophy"],
    themeIds: ["morality", "power"],
    description: "Критика традиционной морали и подготовка к переоценке всех ценностей.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["philosophy-and-thought"]
  },
  {
    id: "thus-spoke-zarathustra",
    title: "Так говорил Заратустра",
    originalTitle: "Also sprach Zarathustra",
    alternativeTitles: ["Thus Spoke Zarathustra"],
    authorId: "nietzsche",
    authorName: "Фридрих Ницше",
    originalLanguage: "de",
    availableLanguages: ["de", "ru"],
    publicationYear: 1883,
    countryId: "germany",
    centuryId: "19",
    epochId: "19th-century",
    movementId: null,
    genreIds: ["philosophy", "poem"],
    themeIds: ["morality", "identity"],
    description: "Философская поэма о сверхчеловеке и вечном возвращении.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["philosophy-and-thought"]
  },
  {
    id: "the-antichrist",
    title: "Антихрист",
    originalTitle: "Der Antichrist",
    alternativeTitles: ["The Antichrist"],
    authorId: "nietzsche",
    authorName: "Фридрих Ницше",
    originalLanguage: "de",
    availableLanguages: ["de", "ru"],
    publicationYear: 1888,
    countryId: "germany",
    centuryId: "19",
    epochId: "19th-century",
    movementId: null,
    genreIds: ["philosophy"],
    themeIds: ["faith", "morality"],
    description: "Резкая критика христианской морали как жизнеотрицающей системы ценностей.",
    cover: null,
    files: [
      { format: "plaintext", url: `${import.meta.env.BASE_URL}books/antichrist.txt` }
    ],
    rightsStatus: "public-domain",
    collectionIds: ["philosophy-and-thought"]
  },
  {
    id: "mrs-dalloway",
    title: "Миссис Дэллоуэй",
    originalTitle: "Mrs Dalloway",
    alternativeTitles: [],
    authorId: "woolf",
    authorName: "Вирджиния Вулф",
    originalLanguage: "en",
    availableLanguages: ["en", "ru"],
    publicationYear: 1925,
    countryId: "england",
    centuryId: "20",
    epochId: "modernism",
    movementId: "modernism",
    genreIds: ["novel"],
    themeIds: ["identity", "society"],
    description: "Один день из жизни героини, рассказанный через поток сознания.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: []
  },
  {
    id: "to-the-lighthouse",
    title: "На маяк",
    originalTitle: "To the Lighthouse",
    alternativeTitles: [],
    authorId: "woolf",
    authorName: "Вирджиния Вулф",
    originalLanguage: "en",
    availableLanguages: ["en", "ru"],
    publicationYear: 1927,
    countryId: "england",
    centuryId: "20",
    epochId: "modernism",
    movementId: "modernism",
    genreIds: ["novel"],
    themeIds: ["family", "identity"],
    description: "Роман о времени, памяти и семье, рассказанный без привычного сюжета.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: []
  },
  {
    id: "picture-of-dorian-gray",
    title: "Портрет Дориана Грея",
    originalTitle: "The Picture of Dorian Gray",
    alternativeTitles: [],
    authorId: "wilde",
    authorName: "Оскар Уайльд",
    originalLanguage: "en",
    availableLanguages: ["en", "ru"],
    publicationYear: 1890,
    countryId: "ireland",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "aestheticism",
    genreIds: ["novel"],
    themeIds: ["morality", "identity"],
    description: "Роман о цене вечной молодости и невидимой цене порока.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: []
  },
  {
    id: "huckleberry-finn",
    title: "Приключения Гекльберри Финна",
    originalTitle: "Adventures of Huckleberry Finn",
    alternativeTitles: [],
    authorId: "twain",
    authorName: "Марк Твен",
    originalLanguage: "en",
    availableLanguages: ["en", "ru"],
    publicationYear: 1884,
    countryId: "usa",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["novel"],
    themeIds: ["coming-of-age", "society"],
    description: "Путешествие по Миссисипи как взросление и столкновение с моралью общества.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["great-19th-century-novels"]
  },
  {
    id: "pride-and-prejudice",
    title: "Гордость и предубеждение",
    originalTitle: "Pride and Prejudice",
    alternativeTitles: [],
    authorId: "austen",
    authorName: "Джейн Остин",
    originalLanguage: "en",
    availableLanguages: ["en", "ru"],
    publicationYear: 1813,
    countryId: "england",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["novel"],
    themeIds: ["love", "society"],
    description: "Роман нравов о браке, гордости и первом впечатлении.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["great-19th-century-novels"]
  },
  {
    id: "iliad",
    title: "Илиада",
    originalTitle: "Ἰλιάς",
    alternativeTitles: ["Iliad"],
    authorId: "homer",
    authorName: "Гомер",
    originalLanguage: "grc",
    availableLanguages: ["grc", "ru"],
    publicationYear: null,
    countryId: "ancient-greece",
    centuryId: "8-bc",
    epochId: "antiquity",
    movementId: "epic",
    genreIds: ["epic-poem"],
    themeIds: ["war-and-peace", "power"],
    description: "Эпос о гневе Ахилла и последних неделях Троянской войны.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["foundational-texts"]
  },
  {
    id: "odyssey",
    title: "Одиссея",
    originalTitle: "Ὀδύσσεια",
    alternativeTitles: ["Odyssey"],
    authorId: "homer",
    authorName: "Гомер",
    originalLanguage: "grc",
    availableLanguages: ["grc", "ru"],
    publicationYear: null,
    countryId: "ancient-greece",
    centuryId: "8-bc",
    epochId: "antiquity",
    movementId: "epic",
    genreIds: ["epic-poem"],
    themeIds: ["identity", "family"],
    description: "Долгое возвращение домой как испытание хитрости и терпения.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["foundational-texts"]
  },
  {
    id: "dead-souls",
    title: "Мёртвые души",
    originalTitle: null,
    alternativeTitles: ["Dead Souls"],
    authorId: "gogol",
    authorName: "Николай Гоголь",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1842,
    countryId: "russia",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["novel", "poem"],
    themeIds: ["society", "morality"],
    description: "Сатирическая поэма-роман о скупке умерших крестьянских душ.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["russian-classics"]
  },
  {
    id: "the-overcoat",
    title: "Шинель",
    originalTitle: null,
    alternativeTitles: ["The Overcoat"],
    authorId: "gogol",
    authorName: "Николай Гоголь",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1842,
    countryId: "russia",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["short-story"],
    themeIds: ["society", "identity"],
    description: "История маленького человека и его единственной мечты.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["russian-classics"]
  },
  {
    id: "eugene-onegin",
    title: "Евгений Онегин",
    originalTitle: null,
    alternativeTitles: ["Eugene Onegin"],
    authorId: "pushkin",
    authorName: "Александр Пушкин",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1833,
    countryId: "russia",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "romanticism",
    genreIds: ["novel-in-verse"],
    themeIds: ["love", "society"],
    description: "Роман в стихах о скуке, чести и упущенной любви.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["russian-classics"]
  },
  {
    id: "the-captains-daughter",
    title: "Капитанская дочка",
    originalTitle: null,
    alternativeTitles: ["The Captain's Daughter"],
    authorId: "pushkin",
    authorName: "Александр Пушкин",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1836,
    countryId: "russia",
    centuryId: "19",
    epochId: "19th-century",
    movementId: "realism",
    genreIds: ["novel"],
    themeIds: ["love", "morality"],
    description: "Историческая повесть о чести на фоне пугачёвского восстания.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: ["russian-classics"]
  },
  {
    id: "evening-album",
    title: "Вечерний альбом",
    originalTitle: null,
    alternativeTitles: [],
    authorId: "tsvetaeva",
    authorName: "Марина Цветаева",
    originalLanguage: "ru",
    availableLanguages: ["ru"],
    publicationYear: 1910,
    countryId: "russia",
    centuryId: "20",
    epochId: "silver-age",
    movementId: "symbolism",
    genreIds: ["poetry-collection"],
    themeIds: ["identity", "love"],
    description: "Дебютный сборник стихов, написанный ещё в гимназические годы.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: []
  },
  {
    id: "the-metamorphosis",
    title: "Превращение",
    originalTitle: "Die Verwandlung",
    alternativeTitles: ["The Metamorphosis"],
    authorId: "kafka",
    authorName: "Франц Кафка",
    originalLanguage: "de",
    availableLanguages: ["de", "ru"],
    publicationYear: 1915,
    countryId: "austria-hungary",
    centuryId: "20",
    epochId: "modernism",
    movementId: "modernism",
    genreIds: ["novella"],
    themeIds: ["alienation", "family", "identity"],
    description: "Повесть о человеке, превратившемся в насекомое, и о равнодушии семьи.",
    cover: null,
    files: [],
    rightsStatus: "public-domain",
    collectionIds: []
  }

];
