// Omnia-owned normalized reader assets that have completed offline ingestion.
const NORMALIZED_WORK_IDS = new Set<string>([
  "war-and-peace",
  "anna-karenina",
  "crime-and-punishment",
  "brothers-karamazov",
  "faust",
  "hamlet",
  "romeo-and-juliet",
  "divine-comedy",
  "beyond-good-and-evil",
  "thus-spoke-zarathustra",
  "mrs-dalloway",
  "picture-of-dorian-gray",
  "huckleberry-finn",
  "iliad",
  "odyssey",
  "the-metamorphosis",
  "to-the-lighthouse",
  "sense-and-sensibility",
  "emma",
  "mansfield-park",
  "northanger-abbey",
  "persuasion",
  "oliver-twist",
  "great-expectations",
  "a-tale-of-two-cities",
  "david-copperfield",
  "bleak-house",
  "hard-times",
  "a-christmas-carol",
  "nicholas-nickleby",
  "jane-eyre",
  "villette",
  "wuthering-heights",
  "agnes-grey",
  "tenant-of-wildfell-hall",
  "middlemarch",
  "silas-marner",
  "adam-bede",
  "mill-on-the-floss",
  "tess-of-the-durbervilles",
  "jude-the-obscure",
  "far-from-the-madding-crowd",
  "mayor-of-casterbridge",
  "return-of-the-native",
  "heart-of-darkness",
  "lord-jim",
  "secret-agent",
  "nostromo",
  "treasure-island",
  "jekyll-and-hyde",
  "kidnapped",
  "moby-dick",
  "typee",
  "age-of-innocence",
  "house-of-mirth",
  "ethan-frome",
  "turn-of-the-screw",
  "portrait-of-a-lady",
  "daisy-miller",
  "dubliners",
  "portrait-of-the-artist",
  "great-gatsby",
  "this-side-of-paradise",
  "sons-and-lovers",
  "women-in-love",
  "importance-of-being-earnest",
  "canterville-ghost"
]);

export function getNormalizedAssetUrl(workId: string): string | null {
  if (!NORMALIZED_WORK_IDS.has(workId)) return null;
  const configuredBase = import.meta.env?.BASE_URL ?? "/reader-app-ANKI/";
  const base = configuredBase.endsWith("/") ? configuredBase : `${configuredBase}/`;
  return `${base}books-normalized/${workId}.json`;
}

export function hasNormalizedAsset(workId: string): boolean {
  return NORMALIZED_WORK_IDS.has(workId);
}
