import type { ManifestEntry } from "../ingestion/applyManifest";

// Generated by scripts/catalog/generateBatch50.ts together with the cached
// Gutenberg records and normalized Omnia assets.
export const GUTENBERG_BATCH_50_MANIFEST: ManifestEntry[] = [];
