import type { ExternalBookRecord } from "../ingestion/types";

// Generated by scripts/catalog/generateBatch50.ts. Kept as a checked-in cache
// so runtime catalog construction never depends on network access.
export const GUTENBERG_BATCH_50_RECORDS: Record<string, ExternalBookRecord> = {};
