-- AESTESIS CATALOG BOUNDARY -- seed v1
-- 61 live production work_ids verified as published, catalog_ready, backed by
-- ready normalized anki-json content, and carrying public-domain rights.
-- age_band is deliberately NULL: contentMaturity is a reader-context gate,
-- not a per-book age classification. sort_order is fallback browse order only.

insert into public.aestesis_catalog_works (work_id, enabled, sort_order, age_band) values
  ('alices-adventures-in-wonderland', true, 10, null),
  ('a-wonder-book-for-girls-and-boys', true, 20, null),
  ('the-happy-prince-and-other-tales', true, 30, null),
  ('the-canterville-ghost', true, 40, null),
  ('a-christmas-carol-in-prose-being-a-ghost-story-of-christmas', true, 50, null),
  ('household-stories-by-the-brothers-grimm', true, 60, null),
  ('the-adventures-of-tom-sawyer-complete', true, 70, null),
  ('treasure-island', true, 80, null),
  ('draculas-guest', true, 90, null),
  ('the-prisoner-of-zenda', true, 100, null),
  ('the-call-of-the-wild', true, 110, null),
  ('through-the-looking-glass', true, 120, null),
  ('tom-sawyer-abroad', true, 130, null),
  ('emma', true, 140, null),
  ('northanger-abbey', true, 150, null),
  ('tom-sawyer-detective', true, 160, null),
  ('the-prince-and-the-pauper', true, 170, null),
  ('pride-and-prejudice', true, 180, null),
  ('sense-and-sensibility', true, 190, null),
  ('a-house-of-pomegranates', true, 200, null),
  ('ws-q2349094', true, 210, null),
  ('silas-marner', true, 220, null),
  ('ws-q4551661', true, 230, null),
  ('the-captains-daughter', true, 240, null),
  ('huckleberry-finn', true, 250, null),
  ('white-fang', true, 260, null),
  ('dracula', true, 270, null),
  ('persuasion', true, 280, null),
  ('the-hunting-of-the-snark-an-agony-in-eight-fits', true, 290, null),
  ('mansfield-park', true, 300, null),
  ('a-connecticut-yankee-in-king-arthurs-court', true, 310, null),
  ('typee-a-romance-of-the-south-seas', true, 320, null),
  ('hard-times', true, 330, null),
  ('eugene-onegin', true, 340, null),
  ('the-strange-case-of-dr-jekyll-and-mr-hyde', true, 350, null),
  ('a-tale-of-two-cities', true, 360, null),
  ('the-sea-wolf', true, 370, null),
  ('ws-q1304649', true, 380, null),
  ('oliver-twist', true, 390, null),
  ('david-copperfield', true, 400, null),
  ('nicholas-nickleby', true, 410, null),
  ('adam-bede', true, 420, null),
  ('romeo-and-juliet', true, 430, null),
  ('sylvie-and-bruno', true, 440, null),
  ('dead-souls', true, 450, null),
  ('middlemarch', true, 460, null),
  ('ws-q1215018', true, 470, null),
  ('the-mysterious-stranger-a-romance', true, 480, null),
  ('bartleby-the-scrivener-a-story-of-wall-street', true, 490, null),
  ('great-expectations', true, 500, null),
  ('bleak-house', true, 510, null),
  ('ws-q129778', true, 520, null),
  ('sorrows-of-young-werther', true, 530, null),
  ('hamlet', true, 540, null),
  ('moby-dick-or-the-whale', true, 550, null),
  ('war-and-peace', true, 560, null),
  ('picture-of-dorian-gray', true, 570, null),
  ('the-metamorphosis', true, 580, null),
  ('martin-eden', true, 590, null),
  ('crime-and-punishment', true, 600, null),
  ('brothers-karamazov', true, 610, null)
on conflict (work_id) do nothing;
