// NOTES + HIGHLIGHTS PHASE: real, Supabase-backed highlights/notes for an
// authenticated visitor -- public.annotations (see
// supabase/sql/annotations.sql for the schema/RLS; that migration's own
// header comment explains why this is Edition-specific, why one table
// covers both highlights and notes, and exactly what the anchor
// (page_index/start_offset/end_offset/context) means and why it's stable).
// Same shape as src/api/userLibrary.ts / src/api/readerProgress.ts: plain
// fetch() against PostgREST, the public "publishable key" as `apikey`, a
// real user access token as `Authorization: Bearer`, RLS itself (not this
// file) restricting every request to auth.uid() = user_id -- no
// service_role, no Edge Function, because there is nothing here an
// authenticated visitor's own RLS grant doesn't already cover.
import { getValidAccessToken } from "../auth/supabaseAuth";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "../auth/supabaseAuth";

const TABLE_ENDPOINT = `${SUPABASE_URL}/rest/v1/annotations`;

export interface Annotation {
  id: string;
  userId: string;
  workId: string;
  editionId: string;
  quoteText: string;
  noteText: string | null;
  pageIndex: number;
  startOffset: number;
  endOffset: number;
  contextBefore: string | null;
  contextAfter: string | null;
  createdAt: string;
  updatedAt: string;
}

interface AnnotationRow {
  id: string;
  user_id: string;
  work_id: string;
  edition_id: string;
  quote_text: string;
  note_text: string | null;
  page_index: number;
  start_offset: number;
  end_offset: number;
  context_before: string | null;
  context_after: string | null;
  created_at: string;
  updated_at: string;
}

function fromRow(row: AnnotationRow): Annotation {
  return {
    id: row.id,
    userId: row.user_id,
    workId: row.work_id,
    editionId: row.edition_id,
    quoteText: row.quote_text,
    noteText: row.note_text,
    pageIndex: row.page_index,
    startOffset: row.start_offset,
    endOffset: row.end_offset,
    contextBefore: row.context_before,
    contextAfter: row.context_after,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

const NOT_AUTHENTICATED = "Не авторизован.";

async function authHeaders(extra?: Record<string, string>): Promise<Record<string, string>> {
  const token = await getValidAccessToken();
  if (!token) throw new Error(NOT_AUTHENTICATED);
  return {
    "apikey": SUPABASE_PUBLISHABLE_KEY,
    "Authorization": `Bearer ${token}`,
    "Content-Type": "application/json",
    ...extra
  };
}

async function throwOnError(response: Response, action: string): Promise<void> {
  if (response.ok) return;
  const detail = await response.text().catch(() => "");
  console.error(`annotations ${action} failed (${response.status}):`, detail);
  throw new Error(`Не удалось выполнить действие с заметками (${action}).`);
}

// Reader-perf requirement: called with exactly ONE edition_id, never
// "give me everything" -- opening a book only ever needs that book's own
// highlights. listAnnotationsForUser() below is the separate, deliberately
// different call the Notes screen uses instead.
export async function listAnnotationsForEdition(editionId: string): Promise<Annotation[]> {
  const headers = await authHeaders();
  const response = await fetch(
    `${TABLE_ENDPOINT}?edition_id=eq.${encodeURIComponent(editionId)}&select=*&order=start_offset.asc`,
    { headers }
  );
  await throwOnError(response, "list-edition");
  const rows = (await response.json()) as AnnotationRow[];
  return rows.map(fromRow);
}

// Notes screen only: every annotation this visitor has, across every
// Work/Edition -- a single request, not one per book (see
// NotesView.tsx's own comment on batching Work metadata on top of this
// with fetchAndMergeWorksByIds, the same mechanism My Library already
// uses). This is the one legitimate "give me everything" read in this
// file; Reader itself never calls it.
export async function listAnnotationsForUser(): Promise<Annotation[]> {
  const headers = await authHeaders();
  const response = await fetch(
    `${TABLE_ENDPOINT}?select=*&order=updated_at.desc`,
    { headers }
  );
  await throwOnError(response, "list-user");
  const rows = (await response.json()) as AnnotationRow[];
  return rows.map(fromRow);
}

export interface CreateAnnotationInput {
  // CLIENT UUID: generated by the caller (readerEngine.ts's
  // runSaveAnnotation, via crypto.randomUUID()) once, before the
  // optimistic insert, and reused here unchanged as the row's real,
  // final id -- never a temporary "optimistic-*" placeholder that gets
  // swapped for a server-assigned id later. Postgres allows an explicit
  // INSERT value for a column with `default gen_random_uuid()` (the
  // column's own DEFAULT just never fires), and RLS's
  // `with check (auth.uid() = user_id)` on annotations_insert_own applies
  // exactly the same regardless of who chose the id -- so this is safe
  // without any migration change.
  id: string;
  userId: string;
  workId: string;
  editionId: string;
  quoteText: string;
  pageIndex: number;
  startOffset: number;
  endOffset: number;
  contextBefore: string | null;
  contextAfter: string | null;
}

// A fresh row every call, on purpose -- the migration deliberately has no
// UNIQUE constraint on the anchor (a visitor may highlight the same
// fragment twice, or leave two different notes on it), so this is a plain
// INSERT, never an upsert, and needs no ?on_conflict= (unlike
// addToLibrary/saveProgress, which upsert on a real natural key).
export async function createAnnotation(input: CreateAnnotationInput): Promise<Annotation> {
  const headers = await authHeaders({ "Prefer": "return=representation" });
  const response = await fetch(TABLE_ENDPOINT, {
    method: "POST",
    headers,
    body: JSON.stringify({
      id: input.id,
      user_id: input.userId,
      work_id: input.workId,
      edition_id: input.editionId,
      quote_text: input.quoteText,
      page_index: input.pageIndex,
      start_offset: input.startOffset,
      end_offset: input.endOffset,
      context_before: input.contextBefore,
      context_after: input.contextAfter
    })
  });
  await throwOnError(response, "create");
  const rows = (await response.json()) as AnnotationRow[];
  const row = rows[0];
  if (!row) throw new Error("Не удалось сохранить выделение.");
  return fromRow(row);
}

// note_text: null clears an existing note back to "just a highlight" --
// callers pass null explicitly rather than omitting the field, so this
// never silently leaves a stale note behind.
export async function updateAnnotationNote(id: string, noteText: string | null): Promise<Annotation> {
  const headers = await authHeaders({ "Prefer": "return=representation" });
  const response = await fetch(`${TABLE_ENDPOINT}?id=eq.${encodeURIComponent(id)}`, {
    method: "PATCH",
    headers,
    body: JSON.stringify({ note_text: noteText, updated_at: new Date().toISOString() })
  });
  await throwOnError(response, "update-note");
  const rows = (await response.json()) as AnnotationRow[];
  const row = rows[0];
  if (!row) throw new Error("Не удалось обновить заметку.");
  return fromRow(row);
}

// Deletes ONLY this one annotation row -- RLS already restricts it to the
// caller's own rows, and this never touches reader_progress/user_library
// or any other annotation (no cascading deletes anywhere in this schema).
// Safe to call repeatedly: deleting an id that's already gone matches zero
// rows, not an error.
export async function deleteAnnotation(id: string): Promise<void> {
  const headers = await authHeaders({ "Prefer": "return=minimal" });
  const response = await fetch(`${TABLE_ENDPOINT}?id=eq.${encodeURIComponent(id)}`, {
    method: "DELETE",
    headers
  });
  await throwOnError(response, "delete");
}
