export interface Batch50Candidate {
  workId: string;
  title: string;
  aliases: string[];
  authorQuery: string;
}

export const BATCH50_CANDIDATES: Batch50Candidate[] = [
  { workId: "sense-and-sensibility", title: "Sense and Sensibility", aliases: ["Sense and Sensibility"], authorQuery: "Jane Austen" },
  { workId: "emma", title: "Emma", aliases: ["Emma"], authorQuery: "Jane Austen" },
  { workId: "mansfield-park", title: "Mansfield Park", aliases: ["Mansfield Park"], authorQuery: "Jane Austen" },
  { workId: "northanger-abbey", title: "Northanger Abbey", aliases: ["Northanger Abbey"], authorQuery: "Jane Austen" },
  { workId: "persuasion", title: "Persuasion", aliases: ["Persuasion"], authorQuery: "Jane Austen" },
  { workId: "oliver-twist", title: "Oliver Twist", aliases: ["Oliver Twist"], authorQuery: "Charles Dickens" },
  { workId: "great-expectations", title: "Great Expectations", aliases: ["Great Expectations"], authorQuery: "Charles Dickens" },
  { workId: "a-tale-of-two-cities", title: "A Tale of Two Cities", aliases: ["A Tale of Two Cities"], authorQuery: "Charles Dickens" },
  { workId: "david-copperfield", title: "David Copperfield", aliases: ["David Copperfield"], authorQuery: "Charles Dickens" },
  { workId: "bleak-house", title: "Bleak House", aliases: ["Bleak House"], authorQuery: "Charles Dickens" },
  { workId: "hard-times", title: "Hard Times", aliases: ["Hard Times"], authorQuery: "Charles Dickens" },
  { workId: "a-christmas-carol", title: "A Christmas Carol", aliases: ["A Christmas Carol"], authorQuery: "Charles Dickens" },
  { workId: "nicholas-nickleby", title: "Nicholas Nickleby", aliases: ["Nicholas Nickleby"], authorQuery: "Charles Dickens" },
  { workId: "jane-eyre", title: "Jane Eyre", aliases: ["Jane Eyre"], authorQuery: "Charlotte Bronte" },
  { workId: "villette", title: "Villette", aliases: ["Villette"], authorQuery: "Charlotte Bronte" },
  { workId: "wuthering-heights", title: "Wuthering Heights", aliases: ["Wuthering Heights"], authorQuery: "Emily Bronte" },
  { workId: "agnes-grey", title: "Agnes Grey", aliases: ["Agnes Grey"], authorQuery: "Anne Bronte" },
  { workId: "tenant-of-wildfell-hall", title: "The Tenant of Wildfell Hall", aliases: ["The Tenant of Wildfell Hall", "Tenant of Wildfell Hall"], authorQuery: "Anne Bronte" },
  { workId: "middlemarch", title: "Middlemarch", aliases: ["Middlemarch"], authorQuery: "George Eliot" },
  { workId: "silas-marner", title: "Silas Marner", aliases: ["Silas Marner"], authorQuery: "George Eliot" },
  { workId: "adam-bede", title: "Adam Bede", aliases: ["Adam Bede"], authorQuery: "George Eliot" },
  { workId: "mill-on-the-floss", title: "The Mill on the Floss", aliases: ["The Mill on the Floss", "Mill on the Floss"], authorQuery: "George Eliot" },
  { workId: "tess-of-the-durbervilles", title: "Tess of the d'Urbervilles", aliases: ["Tess of the d'Urbervilles", "Tess of the D'Urbervilles"], authorQuery: "Thomas Hardy" },
  { workId: "jude-the-obscure", title: "Jude the Obscure", aliases: ["Jude the Obscure"], authorQuery: "Thomas Hardy" },
  { workId: "far-from-the-madding-crowd", title: "Far from the Madding Crowd", aliases: ["Far from the Madding Crowd"], authorQuery: "Thomas Hardy" },
  { workId: "mayor-of-casterbridge", title: "The Mayor of Casterbridge", aliases: ["The Mayor of Casterbridge", "Mayor of Casterbridge"], authorQuery: "Thomas Hardy" },
  { workId: "return-of-the-native", title: "The Return of the Native", aliases: ["The Return of the Native", "Return of the Native"], authorQuery: "Thomas Hardy" },
  { workId: "heart-of-darkness", title: "Heart of Darkness", aliases: ["Heart of Darkness"], authorQuery: "Joseph Conrad" },
  { workId: "lord-jim", title: "Lord Jim", aliases: ["Lord Jim"], authorQuery: "Joseph Conrad" },
  { workId: "secret-agent", title: "The Secret Agent", aliases: ["The Secret Agent", "Secret Agent"], authorQuery: "Joseph Conrad" },
  { workId: "nostromo", title: "Nostromo", aliases: ["Nostromo"], authorQuery: "Joseph Conrad" },
  { workId: "treasure-island", title: "Treasure Island", aliases: ["Treasure Island"], authorQuery: "Robert Louis Stevenson" },
  { workId: "jekyll-and-hyde", title: "The Strange Case of Dr. Jekyll and Mr. Hyde", aliases: ["The Strange Case of Dr. Jekyll and Mr. Hyde", "Strange Case of Dr Jekyll and Mr Hyde", "Dr. Jekyll and Mr. Hyde"], authorQuery: "Robert Louis Stevenson" },
  { workId: "kidnapped", title: "Kidnapped", aliases: ["Kidnapped"], authorQuery: "Robert Louis Stevenson" },
  { workId: "moby-dick", title: "Moby Dick", aliases: ["Moby Dick", "Moby-Dick; or, The Whale", "Moby-Dick"], authorQuery: "Herman Melville" },
  { workId: "typee", title: "Typee", aliases: ["Typee"], authorQuery: "Herman Melville" },
  { workId: "age-of-innocence", title: "The Age of Innocence", aliases: ["The Age of Innocence", "Age of Innocence"], authorQuery: "Edith Wharton" },
  { workId: "house-of-mirth", title: "The House of Mirth", aliases: ["The House of Mirth", "House of Mirth"], authorQuery: "Edith Wharton" },
  { workId: "ethan-frome", title: "Ethan Frome", aliases: ["Ethan Frome"], authorQuery: "Edith Wharton" },
  { workId: "turn-of-the-screw", title: "The Turn of the Screw", aliases: ["The Turn of the Screw", "Turn of the Screw"], authorQuery: "Henry James" },
  { workId: "portrait-of-a-lady", title: "The Portrait of a Lady", aliases: ["The Portrait of a Lady"], authorQuery: "Henry James" },
  { workId: "daisy-miller", title: "Daisy Miller", aliases: ["Daisy Miller"], authorQuery: "Henry James" },
  { workId: "dubliners", title: "Dubliners", aliases: ["Dubliners"], authorQuery: "James Joyce" },
  { workId: "portrait-of-the-artist", title: "A Portrait of the Artist as a Young Man", aliases: ["A Portrait of the Artist as a Young Man", "Portrait of the Artist as a Young Man"], authorQuery: "James Joyce" },
  { workId: "great-gatsby", title: "The Great Gatsby", aliases: ["The Great Gatsby", "Great Gatsby"], authorQuery: "F. Scott Fitzgerald" },
  { workId: "this-side-of-paradise", title: "This Side of Paradise", aliases: ["This Side of Paradise"], authorQuery: "F. Scott Fitzgerald" },
  { workId: "sons-and-lovers", title: "Sons and Lovers", aliases: ["Sons and Lovers"], authorQuery: "D. H. Lawrence" },
  { workId: "women-in-love", title: "Women in Love", aliases: ["Women in Love"], authorQuery: "D. H. Lawrence" },
  { workId: "importance-of-being-earnest", title: "The Importance of Being Earnest", aliases: ["The Importance of Being Earnest", "Importance of Being Earnest"], authorQuery: "Oscar Wilde" },
  { workId: "canterville-ghost", title: "The Canterville Ghost", aliases: ["The Canterville Ghost", "Canterville Ghost"], authorQuery: "Oscar Wilde" }
];
