import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { BATCH50_CANDIDATES } from "./batch50Config";
import { fetchAndValidate } from "./fetchAndValidate";
import { convertEpubToAnkiJson } from "./epubToAnkiJson";
import { normalizeBook, paginateText } from "../../src/features/reader/engine/pagination";

interface GutendexAuthor { name: string; }
interface GutendexBook { id: number; title: string; authors: GutendexAuthor[]; languages: string[]; formats: Record<string, string>; copyright: boolean | null; }
interface GutendexSearchResponse { results: GutendexBook[]; }

function norm(value: string): string {
  return value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, " ").trim();
}

function titleMatches(bookTitle: string, aliases: string[]): boolean {
  const actual = norm(bookTitle);
  return aliases.some(alias => {
    const wanted = norm(alias);
    return actual === wanted || actual.startsWith(`${wanted} `) || wanted.startsWith(`${actual} `);
  });
}

function authorMatches(authors: GutendexAuthor[], authorQuery: string): boolean {
  const wanted = norm(authorQuery);
  const parts = wanted.split(" ").filter(Boolean);
  const surname = parts[parts.length - 1];
  return authors.some(author => {
    const actual = norm(author.name);
    return actual === wanted || actual.includes(wanted) || wanted.includes(actual) || Boolean(surname && actual.includes(surname));
  });
}

function epubUrl(book: GutendexBook): string | null {
  for (const [mime, url] of Object.entries(book.formats)) if (mime.startsWith("application/epub+zip")) return url;
  return null;
}

async function discover(candidate: (typeof BATCH50_CANDIDATES)[number]): Promise<GutendexBook> {
  const q = `${candidate.title} ${candidate.authorQuery}`;
  const response = await fetch(`https://gutendex.com/books?search=${encodeURIComponent(q)}`);
  if (!response.ok) throw new Error(`${candidate.workId}: Gutendex search failed HTTP ${response.status}`);
  const data = await response.json() as GutendexSearchResponse;
  const viable = data.results.filter(book => book.languages.includes("en") && book.copyright === false && Boolean(epubUrl(book)) && titleMatches(book.title, candidate.aliases) && authorMatches(book.authors, candidate.authorQuery));
  if (viable.length !== 1) {
    const summary = data.results.slice(0, 8).map(book => `${book.id}:${book.title} [${book.authors.map(a => a.name).join(", ")}]`).join(" | ");
    throw new Error(`${candidate.workId}: expected exactly 1 verified Gutenberg match, got ${viable.length}. Search results: ${summary}`);
  }
  return viable[0];
}

async function main(): Promise<void> {
  const outDir = "public/books-normalized";
  mkdirSync(outDir, { recursive: true });
  const ids: Record<string, string> = {};
  let totalChars = 0;
  let totalPages = 0;

  for (const candidate of BATCH50_CANDIDATES) {
    console.log(`=== ${candidate.workId} ===`);
    const book = await discover(candidate);
    const url = epubUrl(book);
    if (!url) throw new Error(`${candidate.workId}: matched Gutenberg record has no EPUB URL`);
    console.log(`matched Gutenberg #${book.id}: ${book.title}`);
    const fetched = await fetchAndValidate(url, "epub");
    const conversion = convertEpubToAnkiJson(fetched.bytes);
    const document = conversion.document;
    if (!document.chapters.length) throw new Error(`${candidate.workId}: zero chapters after conversion`);
    const chars = document.chapters.reduce((sum, chapter) => sum + chapter.text.trim().length, 0);
    if (!chars) throw new Error(`${candidate.workId}: zero text after conversion`);
    let pages = 0;
    for (const chapter of document.chapters) pages += paginateText(normalizeBook(chapter.text)).length;
    if (!pages) throw new Error(`${candidate.workId}: zero pages after project pagination`);
    const output = `${outDir}/${candidate.workId}.json`;
    const json = JSON.stringify(document, null, 2);
    writeFileSync(output, json, "utf-8");
    ids[candidate.workId] = String(book.id);
    totalChars += chars;
    totalPages += pages;
    console.log(`${candidate.workId}: PASS gutenberg=${book.id} chapters=${document.chapters.length} chars=${chars} pages=${pages} bytes=${Buffer.byteLength(json)}`);
  }

  if (Object.keys(ids).length !== BATCH50_CANDIDATES.length) throw new Error(`batch incomplete: ${Object.keys(ids).length}/${BATCH50_CANDIDATES.length}`);
  const generated = `// Generated by scripts/ingest/ingestBatch50.ts. Do not hand-edit.\nexport const BATCH50_GUTENBERG_IDS: Record<string, string> = ${JSON.stringify(ids, null, 2)};\n`;
  const idsPath = "src/catalog/batch50SourceIds.ts";
  mkdirSync(dirname(idsPath), { recursive: true });
  writeFileSync(idsPath, generated, "utf-8");
  console.log(`BATCH50 PASS books=${BATCH50_CANDIDATES.length} totalChars=${totalChars} totalPages=${totalPages}`);
}

main().catch(error => { console.error("ingestBatch50: FAILED --", error instanceof Error ? error.message : error); process.exit(1); });
